"""Type stubs for the compiled `odis._odis` extension.

Hand-written: PyO3 cannot express the `lazy=` overloads or the duck-typed
name-set parameters precisely enough to generate this. Kept honest by
`python -m mypy.stubtest odis` in CI.
"""

from collections.abc import Iterable, Iterator, Mapping
from typing import Any, Callable, Literal, final, overload

__all__ = [
    "Concept",
    "ConceptCollection",
    "ConceptGenerator",
    "ConceptIterator",
    "ConceptPairIterator",
    "Drawing",
    "DrawingNode",
    "FormalContext",
    "Implication",
    "ImplicationGenerator",
    "ImplicationIterator",
    "ImplicationList",
    "ImplicationPairIterator",
    "LabelSet",
    "LabelSetIterator",
    "Poset",
    "Titanic",
]

# Layout search budget in milliseconds; None runs to a proven optimum.
_TimeoutMs = int | None

# A set of labels may be given as a real LabelSet or any iterable of names.
_Names = LabelSet | Iterable[str]
_Algorithm = Literal["dimdraw", "sugiyama", "dimflux"]
# DimFlux needs the extents and intents of the concepts, so it is not
# available for a bare poset.
_PosetAlgorithm = Literal["dimdraw", "sugiyama"]

@final
class LabelSet:
    """An immutable, set-like collection of string labels."""
    def __iter__(self) -> LabelSetIterator: ...
    def __contains__(self, name: str, /) -> bool: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def to_frozenset(self) -> frozenset[str]: ...

@final
class LabelSetIterator:
    def __iter__(self) -> LabelSetIterator: ...
    def __next__(self) -> str: ...

@final
class Concept:
    """A formal concept: a matched (extent, intent) pair."""
    @property
    def extent(self) -> LabelSet: ...
    @property
    def intent(self) -> LabelSet: ...
    def __iter__(self) -> ConceptPairIterator: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int, /) -> LabelSet: ...
    def __contains__(self, label: str, /) -> bool: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def to_python(self) -> tuple[frozenset[str], frozenset[str]]: ...

@final
class ConceptPairIterator:
    def __iter__(self) -> ConceptPairIterator: ...
    def __next__(self) -> LabelSet: ...

@final
class ConceptCollection:
    """An eagerly computed, indexable, sliceable sequence of concepts."""
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, idx: int, /) -> Concept: ...
    @overload
    def __getitem__(self, idx: slice, /) -> list[Concept]: ...
    def __iter__(self) -> ConceptIterator: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def sorted(self) -> ConceptCollection: ...
    def to_python(self) -> list[tuple[frozenset[str], frozenset[str]]]: ...

@final
class ConceptIterator:
    def __iter__(self) -> ConceptIterator: ...
    def __next__(self) -> Concept: ...

@final
class ConceptGenerator:
    """Lazy concept iterator. Mutating the source context invalidates it."""
    def __iter__(self) -> ConceptGenerator: ...
    def __next__(self) -> Concept: ...

@final
class Implication:
    """An attribute implication `premise -> conclusion`."""
    @property
    def premise(self) -> LabelSet: ...
    @property
    def conclusion(self) -> LabelSet: ...
    def __iter__(self) -> ImplicationPairIterator: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int, /) -> LabelSet: ...
    def __contains__(self, label: str, /) -> bool: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def to_python(self) -> tuple[frozenset[str], frozenset[str]]: ...

@final
class ImplicationPairIterator:
    def __iter__(self) -> ImplicationPairIterator: ...
    def __next__(self) -> LabelSet: ...

@final
class ImplicationList:
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, idx: int, /) -> Implication: ...
    @overload
    def __getitem__(self, idx: slice, /) -> list[Implication]: ...
    def __iter__(self) -> ImplicationIterator: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def to_python(self) -> list[tuple[frozenset[str], frozenset[str]]]: ...

@final
class ImplicationIterator:
    def __iter__(self) -> ImplicationIterator: ...
    def __next__(self) -> Implication: ...

@final
class ImplicationGenerator:
    """Lazy implication iterator. Mutating the source context invalidates it."""
    def __iter__(self) -> ImplicationGenerator: ...
    def __next__(self) -> Implication: ...

@final
class DrawingNode:
    """One positioned concept node in a `Drawing`."""
    @property
    def index(self) -> int: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def concept(self) -> Concept: ...
    @property
    def object_labels(self) -> list[str]: ...
    @property
    def attribute_labels(self) -> list[str]: ...
    def __repr__(self) -> str: ...

@final
class Drawing:
    """A computed layout: node coordinates plus the covering edges."""
    @property
    def coordinates(self) -> list[tuple[float, float]]: ...
    @property
    def edges(self) -> list[tuple[int, int]]: ...
    @property
    def nodes(self) -> list[DrawingNode]: ...
    def __repr__(self) -> str: ...
    def to_svg(
        self, ctx: FormalContext, width: int = 800, height: int = 600
    ) -> str: ...

@final
class Poset:
    """A partial order that can be drawn without a `FormalContext`."""
    def __new__(
        cls, nodes: list[str], edges: list[tuple[int, int]]
    ) -> Poset: ...
    @property
    def nodes(self) -> list[str]: ...
    @property
    def edges(self) -> list[tuple[int, int]]: ...
    def draw(
        self,
        algorithm: _PosetAlgorithm = "dimdraw",
        timeout_ms: int | None = 1000,
    ) -> Drawing | None: ...
    def draw_svg(
        self,
        algorithm: _PosetAlgorithm = "dimdraw",
        width: int = 800,
        height: int = 600,
        timeout_ms: int | None = 1000,
    ) -> str: ...
    def __repr__(self) -> str: ...

@final
class Titanic:
    """The TITANIC iceberg-lattice algorithm."""
    def __init__(self) -> None: ...
    @overload
    def enumerate(
        self, ctx: FormalContext, min_support: int, *, lazy: Literal[False] = False
    ) -> ConceptCollection: ...
    @overload
    def enumerate(
        self, ctx: FormalContext, min_support: int, *, lazy: Literal[True]
    ) -> ConceptGenerator: ...

@final
class FormalContext:
    """A formal context (G, M, I): objects, attributes and their incidence."""

    name: str

    def __init__(self) -> None: ...
    @staticmethod
    def from_file(path: str) -> FormalContext: ...
    @staticmethod
    def from_dict(mapping: Mapping[str, Iterable[str]]) -> FormalContext: ...
    @property
    def objects(self) -> list[str]: ...
    @property
    def attributes(self) -> list[str]: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    def __len__(self) -> int: ...
    def __contains__(self, obj: str, /) -> bool: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, key: tuple[str, str], /) -> bool: ...
    def __setitem__(self, key: tuple[str, str], value: bool, /) -> None: ...
    def to_file(self, path: str) -> None: ...
    def copy(self) -> FormalContext: ...

    # -- mutation ---------------------------------------------------------
    def add_object(
        self, name: str, attributes: Iterable[str] | None = None
    ) -> None: ...
    def add_attribute(self, name: str) -> None: ...
    def remove_object(self, name: str) -> None: ...
    def remove_attribute(self, name: str) -> None: ...
    def rename_object(self, old_name: str, new_name: str) -> None: ...
    def rename_attribute(self, old_name: str, new_name: str) -> None: ...

    # -- derivation operators ---------------------------------------------
    def extent(self, attributes: _Names) -> LabelSet: ...
    def intent(self, objects: _Names) -> LabelSet: ...
    def attribute_hull(self, attributes: _Names) -> LabelSet: ...
    def object_hull(self, objects: _Names) -> LabelSet: ...
    def upper_neighbor(self, extent: _Names) -> LabelSet: ...

    # -- concepts ---------------------------------------------------------
    @overload
    def concepts(self, *, lazy: Literal[False] = False) -> ConceptCollection: ...
    @overload
    def concepts(self, *, lazy: Literal[True]) -> ConceptGenerator: ...

    # -- implications -----------------------------------------------------
    @overload
    def canonical_basis(
        self, *, lazy: Literal[False] = False
    ) -> ImplicationList: ...
    @overload
    def canonical_basis(self, *, lazy: Literal[True]) -> ImplicationGenerator: ...
    @overload
    def canonical_basis_optimised(
        self, *, lazy: Literal[False] = False
    ) -> ImplicationList: ...
    @overload
    def canonical_basis_optimised(
        self, *, lazy: Literal[True]
    ) -> ImplicationGenerator: ...
    def next_preclosure(
        self,
        implications: ImplicationList | Iterable[Implication],
        current: _Names,
    ) -> LabelSet: ...

    # -- attribute exploration --------------------------------------------
    def attribute_exploration(
        self,
        callback: Callable[[LabelSet, LabelSet], Any],
    ) -> ImplicationList: ...

    # -- drawing ----------------------------------------------------------
    def draw(
        self,
        algorithm: _Algorithm = "dimdraw",
        timeout_ms: int | None = 1000,
    ) -> Drawing | None: ...
    def draw_svg(
        self,
        algorithm: _Algorithm = "dimdraw",
        width: int = 800,
        height: int = 600,
        timeout_ms: int | None = 1000,
    ) -> str: ...
